import React from 'react'
import Head from 'next/head'
import Header from './Header'
import Navigation from './Navigation'

export default function Layout ({ children }) {
  return (
    <>
      <Head>
        <title>Nice Movie and Happy Live</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Navigation />
      {children}
    </>
  )
}
